source:
  type: huggingface
  dataset_name: stanford-oval/ccnews
  split: train
  config: '2020'
  text_template: "{title}\n{plain_text}"

dense_embedder:
  type: sentence_transformer
  model: BAAI/bge-large-en-v1.5
  trust_remote_code: true
  batch_size: 64
  dtype: bfloat16
  max_tokens: 512

pipeline:
  chunk_size: 10000 # chunk size for processing the dataset in batches
  num_workers: 2

storage:
  type: s3
  s3_bucket: qdrant--vectorforge
  s3_prefix: stanford-oval--ccnews/baai_bge_large_en_v1.5/2020
  output_dir: /tmp/vectorforge