source:
  type: huggingface_parquet
  dataset_name: HuggingFaceFW/finewiki
  split: train
  path_filter: "data/enwiki/*"
  prefetch: true
  text_template: "Title: {title}\nText: {text}"

dense_embedder:
  type: sentence_transformer
  model: sentence-transformers/all-MiniLM-L6-v2
  trust_remote_code: true
  batch_size: 64
  dtype: bfloat16
  max_tokens: 256

sparse_embedder:                                                                                        
  type: fastembed                                                                                     
  model: Qdrant/bm25                                                                                  
  batch_size: 256

storage:
  type: hf
  repo_id: nleroy917/finewiki-all-mini-en
  private: false
  output_dir: /tmp/vectorforge

resources:
  accelerators: A10G:1
  instance_type: g5.2xlarge
  cloud: aws
  use_spot: true
  disk_size: 150
  image_id:
    us-east-1: ami-0038d79e7270bb987
    us-west-2: ami-08a03808395c1b31f
    us-east-2: ami-0a28b3d7e7c9192a7
  any_of:
    - region: us-east-1
    - region: us-west-2

pipeline:
  chunk_size: 1000
  num_workers: 2
  max_text_length: 8192
  shard_by_rank: true
  rendered_text_column: rendered_text