source:
  type: huggingface
  dataset_name: corag/kilt-corpus
  split: train
  text_template: "Title: {title}\n\nContents: {contents}"

dense_embedder:
  type: sentence_transformer
  model: intfloat/multilingual-e5-large
  trust_remote_code: true
  batch_size: 64
  dtype: bfloat16
  max_tokens: 256
  truncate: true

pipeline:
  chunk_size: 100000
  num_workers: 2

storage:
  type: s3
  s3_bucket: qdrant--vectorforge
  s3_prefix: corag--kilt-corpus/embed-multilingual-e5-large
  output_dir: /tmp/vectorforge