source:
  type: huggingface
  dataset_name: OpenAssistant/oasst1
  split: train
  text_field: text

embedder:
  type: openai
  model: text-embedding-3-small
  dimensions: 1536

pipeline:
  chunk_size: 10000
  num_workers: 2

storage:
  type: s3
  s3_bucket: qdrant---vectorforge
  s3_prefix: openassistant--oasst1/openai-3-small
  output_dir: /tmp/vectorforge
