source:
  type: huggingface_parquet
  dataset_name: mteb/tweet_sentiment_extraction
  split: train
  text_field: text

dense_embedder:
  type: sentence_transformer
  model: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 128
  dtype: bfloat16

sparse_embedder:                                                                                        
  type: fastembed                                                                                     
  model: Qdrant/bm25                                                                            
  batch_size: 256

storage:
  type: s3
  bucket: qdrant--vectorforge
  prefix: mteb_tweets/all-MiniLM-L6-v2
  output_dir: /tmp/vectorforge

pipeline:
  chunk_size: 1000
  flush_threshold: 10000
  # max_text_length: 8192
  # num_workers: 2
  # shard_by_rank: true

resources:
  cpus: 4
  memory: 32
  cloud: aws
  image_id:
    us-east-1: ami-0038d79e7270bb987
    us-west-2: ami-08a03808395c1b31f
    us-east-2: ami-0a28b3d7e7c9192a7
  