dispatch:
  num_shards: 5
  run_name: arxiv-bge-large

resources:
  cpus: 2
  memory: 16
  cloud: aws

vectors:
  dense:
    type: dense
    column: dense_embedding
    distance: cosine
  sparse:
    type: sparse
    column: sparse_embedding

datasource:
  type: s3
  s3_bucket: qdrant--vectorforge
  s3_prefix: arxiv-papers/embedder-bge-large-en-v1.5/
  id_expression: "vf_point_id(filename, file_row_number)"
  prefetch: true
  payload_fields:
    title: title
    authors: authors
    abstract: abstract
    doi: doi
    submission_date: submission_date
    primary_subject: primary_subject
    arxiv_id: arxiv_id

vectorstore:
  type: qdrant
  collection_name: arxiv-bge-large
  url: ${QDRANT_URL}
  api_key: ${QDRANT_API_KEY}

loader:
  batch_size: 256
  concurrency: 4
