dispatch:
  num_shards: 10
  run_name: finewiki-gte-multilingual

resources:
  cpus: 2
  memory: 8
  cloud: aws
  use_spot: true

vectors:
  dense:
    type: dense
    column: dense_embedding
    distance: cosine
  sparse:
    type: sparse
    column: sparse_embedding

datasource:
  type: s3
  s3_bucket: qdrant--vectorforge
  s3_prefix: finewiki/embed-gte-multilingual-base/
  id_expression: "hash(text)"   # stable content-based IDs
  payload_fields:
    text: text
    title: title
    url: url
    wikidata_id: wikidata_id
    in_language: language
    date_modified: date_modified
    has_math: has_math

vectorstore:
  type: qdrant
  collection_name: finewiki-gte-multilingual-base-en
  url: ${QDRANT_URL}
  api_key: ${QDRANT_API_KEY}
 
loader:
  batch_size: 1000
  concurrency: 8