jobs:
  - config: configs/mteb_tweets_openai.yaml
    gpu: false

  - config: configs/nick007x_arxiv_papers.yaml
    gpu: false

  - config: configs/openassistant_oasst1.yaml
    gpu: false

  # - config: configs/wikipedia_gte.yaml
  #   gpu: A10G
  #   timeout: 7200