dispatch:
  num_shards: 10
  run_name: cohere200M

resources:
  cpus: 2
  memory: 8
  cloud: aws
  use_spot: true

datasource:
  type: s3
  s3_bucket: qdrant---vectorforge
  s3_prefix: cohere--wikipedia/embed-multilingual-v3
  payload_fields:
    text: text
    source: source
    row_id: row_id
    chunk_id: chunk_id
    chunk_index: chunk_index

vectorstore:
  type: qdrant
  collection_name: cohere-wikipedia
  url: ${QDRANT_URL}
  api_key: ${QDRANT_API_KEY}

loader:
  batch_size: 1000
  prefetch_size: 100000
  concurrency: 8
